### ISSUE TITLE
Support pseudo elements

### ISSUE THREAD

**Issue by sastan** [tw-in-js/twind#103]
[Pseudo elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements) like `::before` and `::after` are denoted with a double colon. These can be currently only supported defining them as additional variants ([setup({variants})](https://twind.dev/docs/handbook/advanced/setup.html#variants) and [core variants](https://github.com/tw-in-js/twind/blob/main/src/twind/variants.ts)):

```js
setup({
  variants: {
    before: '&::before',
    after: '&::after',
  }
})

tw`before:block`
```

To support these within Twind I see two options:

1. Adding them to the [core variants](https://github.com/tw-in-js/twind/blob/main/src/twind/variants.ts) (see PR #106):

  ```js
  {
    after: '&::after',
    before: '&::before',
    'first-letter': '&::first-letter',
    'first-line': '&::first-line',
    selection: '&::selection',
  }
  ```

  Usage:

  ```js
  tw`before:block`
  ```

2. Create plugin providing the variants

  ```js
  import { pseudoElements } from '@twind/pseudo-elements'

  setup({
    variants: pseudoElements
  })

  tw`before:block`
  ```

3. Extend the parser using double colon **after** the variant (see PR #105):

  ```js
  tw`before::block`
  ```

Which options do you prefer? Or do you see another way?

/cc @tw-in-js/contributors

**Comment by gojutin** [comment]
I'm still getting to know the library, but it seems like it wouldn't really add any weight to core by supporting these pseudo element. If that is the case, I personally like the idea of them being in core mainly just because it saves an import statement. But, the other thing I am not sure of is how close you are trying to keep the core library to Tailwind. And, obviously, this would be would another fork in the road.

I kind of like the double colon (`before::block`) syntax just because it feels a bit closer to css and other css-in-js solutions. I also think it would be nice to support grouping, but I am not sure how that would look (or work) with double colons.`before::(p-2 block)` ?

**Comment by tylerforesthauser** [comment]
I'm with Justin, I think the double colon idea is good and the PR indicates a 0.18% size increase, which is virtually negligible, in my eyes. I think it's a solid extension to the core and the syntax deviates just enough to act more as an added bonus rather than a substantial departure from the native Tailwind API.

**Comment by sastan** [comment]
> I kind of like the double colon (`before::block`) syntax just because it feels a bit closer to css and other css-in-js solutions. I also think it would be nice to support grouping, but I am not sure how that would look (or work) with double colons.`before::(p-2 block)` ?

Of cause they are supported. Exactly as you imagined: `before::(p-2 block)`
