### ISSUE TITLE
From 0.16.8 to 0.16.9 : ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Shuunen** [tw-in-js/twind#165]
Hi there,

I was using twind for quite some time on my project : https://github.com/Shuunen/what-now/

I'm using `twind/shim` for months without any issues via this 2 lines of code : 

```js
import { setup } from 'twind/shim'`
setup({ mode: 'silent' })
```

My project is in TypeScript, I build a iife package for web with tsup/esbuild.

Until recently, everything was working well, but the lastest upgrade from `0.16.8` to `0.16.9` has bring this error `ReferenceError: require is not defined` on my website.

If I rollback twind to `0.16.8` then build & deploy again : it works as expected, no more error

I looked at https://github.com/tw-in-js/twind/compare/v0.16.8...v0.16.9 , but it's hard to see which commit introduced this, maybe the `chore: deps upgrade` `a501131` ?

If we compare the 2 builds : 0.16.8 on the left & 0.16.9 on the right : 

![image](https://user-images.githubusercontent.com/439158/112760525-8a9a6380-8ff7-11eb-83a4-297e4e2a51a4.png)

We can see that `require("url")` is appearing with the update, there are 2 other occurences of this same require on the build.

**Comment by sastan** [comment]
Sorry, to hear that. I'll look into it ASAP.

**Comment by sastan** [comment]
My first investigation shows that `require` is only used within `*.cjs` files. I suspect your build is using the `main` package json field. I look into your project setup now.

**Comment by danielweck** [comment]
You're using https://github.com/egoist/tsup / https://github.com/evanw/esbuild so you should be able to set `type="module"` in your `package.json`.

**Comment by Shuunen** [comment]
@sastan `"main": "./twind.cjs",` did not changed from 0.16.8 to 0.16.9 , and when I use the same build routine it works on 0.1x.x and until 0.16.8 included

![image](https://user-images.githubusercontent.com/439158/112762297-33988c80-8fff-11eb-9713-c2cc01a6edb2.png)

We can see here it's twind.cjs that has these require now. 

The build of my project has no errors from 0.16.8 to 0.16.9, it's just these require that doesn't like web environments and crash when executed in a browser. 

@danielweck I tried to set `"type": "module",` but it did not affected the build

**Comment by sastan** [comment]
Found it. Your app is loading the Node.js files: `shim.mjs` -> `shim.cjs`. The only place where this can original is from the root package json exports:

```json
{
  "exports": {
    "./shim": {
      "esnext": "./shim/shim.esnext.js",
      "module": "./shim/shim.js",
      "script": "./shim/shim.umd.js",
      "types": "./shim/shim.d.ts",
      "require": "./shim/shim.cjs",
      "node": "./shim/shim.mjs",
      "default": "./shim/shim.js"
    },
  }
}
```

As you see the are several possible conditions. Most bundles should choose `module` or fallback to `default`. I have to check which conditions tsup is using.

**Comment by sastan** [comment]
> @sastan `"main": "./twind.cjs",` did not changed from 0.16.8 to 0.16.9 , and when I use the same build routine it works on 0.1x.x and until 0.16.8 included

But the bundler shouldn't use the cjs file. That is for the server use. There are 2 problems I see:

1. Why is the URL require there? That is from a change in distilt and shouldn't be in files that do not use `import.meta.url`
  - That is causing the build to fail now.
2. Why does tsup use the mjs and therefore cjs file? It should use the js file.

**Comment by Shuunen** [comment]
@sastan ok so ideally which file should be loaded here by the bundler ? 

wrong screen cap above, here is shim.cjs that also have these requires

![image](https://user-images.githubusercontent.com/439158/112762605-cdad0480-9000-11eb-8be5-7af35555a388.png)

**Comment by Shuunen** [comment]
@sastan so because tsup is a wrapper of esbuild I tried to build my web app with esbuild : 

![image](https://user-images.githubusercontent.com/439158/112763253-f84c8c80-9003-11eb-8600-afc66807cf8b.png)

file sizes are pretty different I'm surprised

and most of all it works well with twind 0.16.9

![image](https://user-images.githubusercontent.com/439158/112763328-4bbeda80-9004-11eb-9df2-3f54843614be.png)

I can't explain why there is so much differences between `esbuild src/index.ts --bundle` and `tsup src/index.ts` but this was the issue.

As you pointed out `tsup` is picking the wrong file

**Comment by sastan** [comment]
I think I found the culprint. tsup is using [always setting](https://github.com/egoist/tsup/blob/master/src/index.ts#L160) `node` for the esbuild [platform](https://esbuild.github.io/api/#platform). That leads to including `node` in the conditions. Which leads to `shim/shim.mjs` and `shim/shim.cjs`. 

Changing https://github.com/egoist/tsup/blob/master/src/index.ts#L160 in my local node_modules to `browser` and everything works again.

1. I believe tsup should allow to set the platform. Especially now that esbuild supports the exports package json field.
2. I have to make sure that the un-used `import.meta.url` is not included in the file.

PS:

Our exports conditions try to support as many bundler and Node.js. For example we do not have an `import` condition because of the dual-package hazard.

```
"esnext": most modern syntax
"module": for bundlers
"script": for use with script tag
"types": for typescript
"require": for Node.js require
"node": for Node.js import (wrapper for require)
"default": for bundlers as fallback
```

When using esbuild platform=node the following conditions will be used:

- `node` -> this one leads to the wrong file
- `default`
- `require` -> not used because the module is imported
- `import` -> not there because dual-package hazard

When using esbuild platform=browser the following conditions will be used:

- `default` -> the right one is used
- `browser` -> not there because really ambiguous between bundlers
- `require` -> not used because the module is imported
- `import` -> not there because dual-package hazard

**Comment by Shuunen** [comment]
@sastan thanks for all your explanations, I learnt a lot today, sorry that the issue belong to tsup in the end (see my previous comment)

**Comment by Shuunen** [comment]
twind FTW \o/

**Comment by sastan** [comment]
No worries. Happy to help.
