### ISSUE TITLE
Error: [UNKNOWN_DIRECTIVE] {"rule":"card"}

### ISSUE THREAD

**Issue by sibbng** [tw-in-js/twind#170]
Hi, I have a plugin that adds few components. It works as expected but it throws an error on console.

[Reproduction](https://jspm.org/sandbox#H4sIAAAAAAAAA4VSPW+DMBCd4VdcWUikEEdVVVXIydJ2bqV26RYHu2AFbAsfSVCU/17ADvlY6sWnd3fv3vmZPrx9vH7/fL5DgVW5Cml/QclUvoyEiqCQnAu1CgFoIRjvgy60WS0NArZGLKNK86YUkUsByMroGuEIVmBjZsCMKVs4wW+tK4gKRGNTQjKu5nbbGpZt51zsCO6l4sQWsorCIAhGEq6rr0IIPBPE/xF0tTYOvZZMK4uwaRC1gqWTsjaH5AlMmzxCrRvFBYdNnuQ1a5PnxQJQHDDZFxLF+oYkYzW/UHQMV8214MnLXa9vHh5hcux3CgZx6bjSZDrzRQCmbHKpbArHEepO1Tr8Dga/0ewWjOe9xjgdpF6nTpfCMTxNnZPEWTkYTM4O043mLWQls7az14vwBlM3e4VifFlKPOYKuNyde3slkSvtQ0q6nBvVT+h+Gxl+3R9mHKHFhQIAAA==)

**Comment by danielweck** [comment]
That's probably because `class="card"` is discovered by Twind's shim (which, under the hood, is a mutation / DOM observer), and as the string token `card` is not directly associated with a standard Tailwind class or a plugin name, a warning message is emitted?

By the way, you should probably consider using `preflight` for your base styles, and `plugins` to scope your components (there are different ways of doing this in Twind, e.g. `styles()` is particular suited for this): [esm.codes demo](https://esm.codes/#aW1wb3J0IHsgaCwgcmVuZGVyIH0gZnJvbSAiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvcHJlYWN0IgppbXBvcnQgaHRtIGZyb20gImh0dHBzOi8vY2RuLnNreXBhY2suZGV2L2h0bSIKCmltcG9ydCB7IHNldHVwLCBhcHBseSwgdHcgfSBmcm9tICJodHRwczovL2Nkbi5za3lwYWNrLmRldi90d2luZCIKCmltcG9ydCB7IGNyZWF0ZU9ic2VydmVyIH0gZnJvbSAiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvdHdpbmQvb2JzZXJ2ZSIKCmNvbnN0IGh0bWwgPSBodG0uYmluZChoKQoKY29uc3QgdHdpbmRPYnNlcnZlciA9IGNyZWF0ZU9ic2VydmVyKCkKdHdpbmRPYnNlcnZlci5vYnNlcnZlKGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkKCnNldHVwKHsKcHJlZmxpZ2h0OiB7CiAgYm9keTogewogICAgJ0BhcHBseSc6ICdwLTQgYmctZ3JheS00MDAnLAogIH0sCiAgYnV0dG9uOiB7CiAgICAnQGFwcGx5JzogJ3AtNCByb3VuZGVkIGJnLWJsYWNrIHRleHQtd2hpdGUnLAogICAgJyY6aG92ZXInOiB7CiAgICAgICdAYXBwbHknOiAndGV4dC1yZWQtMjAwIGZvbnQtYm9sZCcKICAgIH0KICB9LAogICcuY2FyZCc6IHsKICAgICdAYXBwbHknOiAnbS00IHAtNCBiZy13aGl0ZSB0ZXh0LWJsYWNrJywKICB9Cn0sCnBsdWdpbnM6IHsKICAncGx1Z2luLXNjb3BlLTEnOiB7CiAgICAnJic6IGFwcGx5YGJvcmRlci0yIHAtMiBib3JkZXItcmVkLTgwMGAsCiAgICBidXR0b246IGFwcGx5YGJvcmRlci00IGJvcmRlci13aGl0ZWAsCiAgICAnLmNhcmQnOiBhcHBseWBib3JkZXItNCBib3JkZXItYmxhY2tgCiAgfSwKICAncGx1Z2luLXNjb3BlLTInOiB7CiAgICAnJic6IGFwcGx5YGJvcmRlci0yIHAtMiBib3JkZXItaW5kaWdvLTgwMGAsCiAgICAnJj4gcCc6IGFwcGx5YGZvbnQtZXh0cmFib2xkIHVwcGVyY2FzZWAsCiAgICBidXR0b246IGFwcGx5YHJvdW5kZWQteGwgYmcteWVsbG93LTIwMCB0ZXh0LXJlZC02MDBgLAogICAgJy5jYXJkJzogewogICAgICAnQGFwcGx5JzogJ3JvdW5kZWQgYmctcmVkLTgwMCB0ZXh0LXdoaXRlJywKICAgICAgJyY+IHNwYW4nOiBhcHBseWB0ZXh0LWJsYWNrYAogICAgfQogIH0sCn0sCn0pCgpjb25zdCBBcHAgPSAoKSA9PiB7CiAgcmV0dXJuIGh0bWxgCgogIDxkaXYgY2xhc3M9InBsdWdpbi1zY29wZS0xIj4KICAgIDxidXR0b24+dGVzdCBidXR0b24gMTwvYnV0dG9uPgogICAgPGRpdiBjbGFzcz0iY2FyZCI+dGVzdCBjYXJkIDE8L2Rpdj4KICA8L2Rpdj4KICA8ZGl2IGNsYXNzPSJwbHVnaW4tc2NvcGUtMiI+CiAgICA8YnV0dG9uPnRlc3QgYnV0dG9uIDI8L2J1dHRvbj4KICAgIDxkaXYgY2xhc3M9ImNhcmQiPnRlc3QgPHNwYW4+Y2FyZDwvc3Bhbj4gMjwvZGl2PgogICAgPHA+cGFyYWdyYXBoPC9wPgogIDwvZGl2PgogIGAKfQoKcmVuZGVyKGh0bWxgPCR7QXBwfSAvPmAsIGRvY3VtZW50LmJvZHkp)

```js
import { h, render } from "https://cdn.skypack.dev/preact"
import htm from "https://cdn.skypack.dev/htm"

import { setup, apply, tw } from "https://cdn.skypack.dev/twind"

import { createObserver } from "https://cdn.skypack.dev/twind/observe"

const html = htm.bind(h)

const twindObserver = createObserver()
twindObserver.observe(document.documentElement)

setup({
preflight: {
  body: {
    '@apply': 'p-4 bg-gray-400',
  },
  button: {
    '@apply': 'p-4 rounded bg-black text-white',
    '&:hover': {
      '@apply': 'text-red-200 font-bold'
    }
  },
  '.card': {
    '@apply': 'm-4 p-4 bg-white text-black',
  }
},
plugins: {
  'plugin-scope-1': {
    '&': apply`border-2 p-2 border-red-800`,
    button: apply`border-4 border-white`,
    '.card': apply`border-4 border-black`
  },
  'plugin-scope-2': {
    '&': apply`border-2 p-2 border-indigo-800`,
    '&> p': apply`font-extrabold uppercase`,
    button: apply`rounded-xl bg-yellow-200 text-red-600`,
    '.card': {
      '@apply': 'rounded bg-red-800 text-white',
      '&> span': apply`text-black`
    }
  },
},
})

const App = () => {
  return html`

  <div class="plugin-scope-1">
    <button>test button 1</button>
    <div class="card">test card 1</div>
  </div>
  <div class="plugin-scope-2">
    <button>test button 2</button>
    <div class="card">test <span>card</span> 2</div>
    <p>paragraph</p>
  </div>
  `
}

render(html`<${App} />`, document.body)
```

**Comment by sastan** [comment]
The `card` class is not a known plugin and leads to the warning. The warnings should help to discover typos in class names. 

Maybe we need to add some ignore list option?

**Comment by danestves** [comment]
![image](https://user-images.githubusercontent.com/31737273/113618660-fdbe5e00-9625-11eb-92b0-4b13ab829813.png)

I also have several errors from classes that i don't have control

**Comment by sastan** [comment]
These messages are not _really_ errors. They are more hints that there may be something wrong. If you have a lot of those you can disables them

```
setup({ mode: 'silent' })
```

In the future II would like to have some kind of `ignorelist`: 

```
setup({
  mode: {
   ignore: [
     /^glide[_\-]/
   ]
  }
})
```

**Comment by lukejacksonn** [comment]
I have seen others get confused/worried about these warnings.. perhaps we should consider turning them off by default.

**Comment by danielweck** [comment]
I find the warning/error message very useful in the context of static SSR + generation of critical CSS (and of "secondary" CSS, in my case as well).
BUT ... it would be nice if we could configure an allowlist via setup(), either regexp, array of regexp, and plain string match too.

**Comment by gojutin** [comment]
2 months later :) 

I agree that the warnings can provide a great value and often the best source to find all my misspelled class names when using the shim (no intellisense). I like the idea of the ignoreList for classes outside of Twind that are known in advance.

I wonder if there is was a way to point at other css files and have all the classes automatically parsed and added into the ignore list. Perhaps a postcss-powered plugin?

**Comment by sastan** [comment]
Implemented in twind v1 as `ignorelist`.

```js
{
  // DO NOT IGNORE rules starting with `^[~#]`, `^css#`, or `^style[~#-]` — these may have been generated by `css()` or `style()`, or are hashed    
  ignorelist: [
		'card',
	    // emotion: `css-`
	    // stitches: `c-`
	    // styled-components: `sc-`and `-sc-
	    // svelte: `svelte-`
	    // vanilla-extract: sprinkles_
	    // goober: `go1234567890`
	    /^((css|s?c|svelte)-|(sprinkles)?_|go\d)|-sc-/,
  ]
}
```

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
