### ISSUE TITLE
twind/shim: Consider suggesting <body hidden> over <html hidden>

### ISSUE THREAD

**Issue by sibbng** [tw-in-js/twind#172]
## Motivation

Hiding `html` will cause background flash if your website depends on dark/multiple themes like:

`<html style="background-color: #111827">`
or inline theming functions like [here](https://github.com/antfu/vitesse/blob/master/index.html#L14-L21).

## Solutions

1. Migrate to `<body hidden>`
2. Also remove `hidden` attribute from `body` alongside `html`.

I would like to send PR if we decide which solution we will follow. But in my opinion we should suggest using `hidden` with `body` in docs nevertheless.

## Alternative solutions

`<body class="block" hidden>`
`<body class="!block" style="display: none">`

**Comment by lukejacksonn** [comment]
Hey, this sounds like a valid point. I've been SSR'ing with critical CSS extraction for a while now and so haven't discovered this nuance yet. If the flashing issue disappears when putting hidden on the body instead of html then it makes sense to move the hidden attribute to the body.

The steps you lay out sounds like it wouldn't be a breaking change either:

- Migrate to <body hidden>
- Also remove hidden attribute from body alongside html.

**Comment by sastan** [comment]
@sibbng Good you opened this issue. I had that on my list since your tweet.

I like the `Also remove hidden attribute from body alongside html.` idea.

**Comment by sastan** [comment]
This will be fixed using _remove `hidden` attribute from `body` alongside `html`_ in the upcoming v1 release.
