### ISSUE TITLE
Custom class name will not work in certain cases

### ISSUE THREAD

**Issue by sohaha** [tw-in-js/twind#179]
The original code is:
```html
<style>
 .cursor {
  border: 10px solid red !important;
}
</style>
<div class="cursor bg-red-400"></div>
```

After the page loads it will become:
```html
<style>
 .cursor {
  border: 10px solid red !important;
}
</style>
<div class="bg-red-400"></div>
```

the expected external style class="cursor" works, but it doesn't work anymore.

**Comment by gojutin** [comment]
Reproduced here: https://codepen.io/gojutin/pen/ExWQmYv

**Comment by sastan** [comment]
This should be fixed in v1.

Please give it a try. Here are some links to get you started:

- [The v1 branch](https://github.com/tw-in-js/twind/tree/next)
- [Reference](https://github.com/tw-in-js/twind/blob/next/documentation/40-reference/README.md) until the website is ready
- [Examples](https://github.com/tw-in-js/twind/tree/next/examples) — the [CDN example](https://github.com/tw-in-js/twind/tree/next/examples/twind-cdn) could be a good start

Closing this for now. Feel free to re-open.
