### ISSUE TITLE
Propose an alternative method to use Twind with Web components and Lit for Firefox and Safari

### ISSUE THREAD

**Issue by gawlk** [tw-in-js/twind#181]
Hi,

Love this project, it works great, ton of great ideas but I have one small issue with it: it's with `adoptedStyleSheets`. It works great with Chrome but as you know it doesn't with Firefox or Safari. As it's the only way to use both twind with web components it's not at all usable in production.

I was wondering if you guys had any idea for an alternative method that would work on more browsers.

If not I fully understand, just thought to point the need for such functionality.

Anyway,

Thanks for you work

**Comment by spitzertim** [comment]
Hi, 

I also really like the project. But as @gawlk mentioned, the implementation from the example is unusable in production due to the limitations in Firefox and Safari. 
This problem applies to lit-element in particular. Even when using a polyfill, lit will analyse a sheet that is put in its static get styles() only once (and too early) and not update the injected styles tags after tw has "learned" about the relevant style classes. 
I have build a workaround that injects a respective style tag from the firstUpdated hook, but it still has a major caveat. When working with conditionally applied classes, twind is updating the sheet again, which then needs to be reflected in the style-tag. I found no way to hook into this. 
You can find an example here https://stackblitz.com/edit/lit-twind-firefox?file=index.js.

I would suggest some kind of hook/event that could be listened for to re-trigger the creation of the style.

Anyways, cool project! Keep up the good work!

**Comment by sastan** [comment]
I'm not that familiar with web components and their frameworks. Would it be possible to use a style element (maybe using the dom sheet) for each web component which is updated per web component instance?

**Comment by Zozman** [comment]
I gotta +1 this as well.  I had a FANTASTIC time using this library over the last week on a project (super easy to use and super easy to tell what's a tailwind class and what's my class) until I noticed that my font sizes weren't right on Firefox and had to rip it all out and replace it with using PostCSS + Tailwind (using lit-element as well).

**Comment by sastan** [comment]
This has been implemented in a new integration: `@twind/with-web-components`.  It supports modern and legacy browsers.

You can view a preview of the docs here: https://next.twind-style.pages.dev/with-web-components. I have added a [Lit](https://lit.dev) example as well in case you are using that: https://next.twind-style.pages.dev/with-lit

This will be released soon (#417). Until is released you can use the pre-release version  (for example [`@twind/with-web-components@next`](https://www.npmjs.com/package/@twind/with-web-components/v/1.0.4-next-20221215155811), [`@twind/core@next`](https://www.npmjs.com/package/@twind/core/v/1.1.0-next-20221215155811) or [`@twind/preset-tailwind@next`](https://www.npmjs.com/package/@twind/preset-tailwind/v/1.1.0-next-20221215155811)).

If you have any issues or questions please re-open this issue.
