### ISSUE TITLE
Hashing can not be disabled - Jest Snapshots are failing

### ISSUE THREAD

**Issue by bwcgn** [tw-in-js/twind#197]
Hey there,

I created a component library which uses twind.
The exported components are utilised in a nextJS project, which as well uses twind.
Hashing is explicit disabled in both setups, but I still seeing hashes when running jest unit test snapshots

Component: 
```tsx
const button = style({
  // Define the base style using tailwindcss class names
  base: 'rounded p-2 transition-colors duration-500 ease-in-out',

  // Declare all possible properties
  variants: {
    // button({ variant: 'primary' })
    variant: {
      primary: `
        text-white
        bg-primary-a
        hover:bg-secondary-a
      `,
      secondary: `
        text-white
        bg-primary-b
        hover:bg-secondary-a
      `,
    },
  },

export const Button: FC<ButtonProps> = ({
  variant = 'primary',
  children,
}: ButtonProps) => {
  return (
    <button
      type="button"
      className={tw(button({ variant }))}
    >
      {children}
    </button>
  );
};
```

nextJS Page:
```tsx
import { Button } from '@my-org/ui';

const Home: React.FC = () => {
  return (
    <>
      <section>
        <Button variant="primary">I am a UI Button</Button>
      </section>
    </>
  );
};
```

Jest output
```
      <button
    -       class="tw-1wke9qu tw-pynqe8"
    +       class="tw-1ilwrz2 tw-1dg5q5"
            type="button"
          >
            I am a UI Button
          </button>
```

Any idea how I can solve this issue? A possible solution would be a webpack loader to render a mocked CSS class on `NODE_ENV=test` ?

**Comment by lukejacksonn** [comment]
Hey there 👋 when using `style` the resultant class name is always hashed. This is done so that it is possible to control specificity levels which makes composing compose different sets of classes possible.

The two class names you are seeing in the DOM are one for the `base` styles and one for the `primary` styles. Going to close here as this is intended behaviour be feel free to ask more questions as to why this is essential either in discussions or on discord!
