### ISSUE TITLE
Tailwind VS Code intellisense doesn't work

### ISSUE THREAD

**Issue by SamLewis0602** [tw-in-js/twind#24]
Hey there, this is an interesting tool. I love that you don't have to mess around with the build step to use it. However, the tailwind intellisense doesn't work when using this library which is killer. I noticed the VS code extension says it will activate if "tailwind css is installed and a tailwind config exists". But obviously there's no reason to install tailwind if using twind. Any thoughts here or something I'm missing? Thanks!

**Comment by SamLewis0602** [comment]
A solution is to just create a default tailwind config and `npm i -D tailwindcss`. That at least gets the extension activated

**Comment by sastan** [comment]
We are planning to create an twind intellisense extension because twind has some syntax features that are not available in tailwindcss (like [grouping](https://github.com/tw-in-js/twind/tree/main/docs/grouping.md)).

The work has already started with a [typescript plugin](https://github.com/tw-in-js/typescript-plugin). This currently provides autocompletion. The plan generate diagnostics within the editor and during tsc compilation.

**Comment by danielweck** [comment]
Twind now offers a pretty powerful TypeScript Language Service plugin, as well as a Visual Studio Code extension that is basically a thin wrapper on top of the plugin.

There's auto-completion based on Tailwind CSS class names and most importantly: Twind's own DSL for groups, etc. There's also hover info popup which shows actual compiled CSS snippets. And there's syntax error highlighting / underlining.

May I suggest closing this issue as resolved, to keep the tracker clean and up to date? :)

**Comment by SamLewis0602** [comment]
I haven't tried it out, but I just went and looked at the VS code extension and it definitely looks good to me! Thanks for following up.
