### ISSUE TITLE
@next TypeError: tw$1.snapshot is not a function in remix

### ISSUE THREAD

**Issue by coltontravers** [tw-in-js/twind#339]
When running the examples for Remix it's outputting the following error: "TypeError: tw$1.snapshot is not a function".

Separately, I also am receiving the following error when running storybook with twind. Though maybe this is a storybook issue, because I have had issues with it in the past.

> ERROR in ./node_modules/twind/twind.js 199:35
Module parse failed: Unexpected token (199:35)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| */ // Colon and dash count of string (ascending)
| function seperatorPrecedence(string) {
>     return string.match(/[-=:;]/g)?.length || 0;
| }
| function atRulePrecedence(css) {
 @ ./app/routes/library.tsx 7:0-32 33:17-19 90:17-19 90:34-37    
 @ ./app/routes.stories.mdx
 @ ./app sync ^\.(?:(?:^|[\\/]|(?:(?:(?!(?:^|[\\/])\.).)*?)[\\/])(?!\.)(?=.)[^\\/]*?\.stories\.(js|mdx))$
 @ ./generated-stories-entry.js

**Comment by sastan** [comment]
Thank you for the report. I will take a look at `tw$1.snapshot is not a function`.

The second issue (webpack) is because twinds code is distributed in es2021 and webpack has a problem parsing modern syntax. I think they are already working on that or there is a solution how to transpile certain node_modules packages.
