### ISSUE TITLE
astro support twind@next

### ISSUE THREAD

**Issue by mybigman** [tw-in-js/twind#371]
A couple of things.

* Is there any plans or can we have support for [astro](https://astro.build/), maybe a plugin?

* How can I use twind@next via shim as installing the package appears to have no shim support that I can see?

I know I can use the `cdn` or just download the file from the `cdn` and reference it locally  but was hoping to use via the package.

**Comment by jca41** [comment]
I second this, a build time `twind` plugin would be amazing. Most astro sites use very little javascript.
Unless there is a way to use the SSR method with astro build time page generation.

**Comment by sastan** [comment]
I would really like to see this as well.  But I don't know when I get to it.

It should be possible with one of the ssr methods: https://github.com/tw-in-js/twind/blob/next/packages/twind/src/ssr.ts

**Comment by rschristian** [comment]
Things might've changed (I haven't checked in a good few months), but in the past there was no way to feed `.astro` files, raw or their compiled HTML output, into any further integrations. That put a stopper into an integration I was building w/ Twind, as any style generation had to be post-build, which was less than ideal.

I've talked with some of the Astro folks since and there was some interest in providing the compiled HTML to integrations to work with but not I'm unsure if that's gone anywhere since.

**Comment by nbbaier** [comment]
Would this be possible with the updates to Astro?
