### ISSUE TITLE
`tw(...)` vs `tw([...])` resulting different class

### ISSUE THREAD

**Issue by rockmandash** [tw-in-js/twind#39]
Please see this minimum example

```js
import { tw } from "twind";

document.body.innerHTML = `
  <div class="${tw("bg-pink-50", "hover:text-pink-900", "p-3")}">
    Not array
  </div>

  <hr />

  <div class="${tw(["bg-pink-50", "hover:text-pink-900", "p-3"])}">
    Array
  </div>
`;
```

[CodeSandbox](https://codesandbox.io/s/tw-vs-tw-resulting-different-class-63d06?file=/src/index.js)

Screenshot

![image](https://user-images.githubusercontent.com/7580792/103340234-85904b80-4abe-11eb-9656-85d5597801de.png)

Everything behind `hover:` will be ignored when using `tw(...)`

**Comment by sastan** [comment]
The second one is the expected behavior as each string should be handled separately eg grouping should not leak into other strings. In that case the first one is bug.

Just a side note: We encourage to use the template literal syntax. Although it should be clearly defined what happens in these case.

@rockmandash  @lukejacksonn What should be the expected behavior? Should it be the same for both cases?

**Comment by rockmandash** [comment]
Hi, @sastan I think it should be the same for both cases.

I'm a Vue developer, I've used `twind` for a week now, and starting to refactor my company's product component to twind, it's an amazing tool!

And I can't use tagged template literal syntax because Vue 2's official cli tool can't compile `.vue`'s HTML with tagged template literal.

So I'm using `tw(...)` and `tw([...])` a lot!

Right now, I'm using `tw([...])` because of this issue, I think I will choose the only format for consistency, which is `tw([...])`.

**Comment by rockmandash** [comment]
The tagged template literal in Vue will break, so I need to stick with `tw([...])`

[CodeSandbox](https://codesandbox.io/s/vue-cant-compile-tagged-template-literal-5pcn8?file=/src/App.vue)

![image](https://user-images.githubusercontent.com/7580792/103342735-4a454b00-4ac5-11eb-822a-8d73d0cfbda3.png)

**Comment by lukejacksonn** [comment]
Hey @rockmandash thanks for the report and glad to hear you are well on your way to migrating your product to Twind!

I agree that if we have documented being able to use variadic function call then it should work in a consistent way to all the other methods of calling tw. However, I would recommend sticking to one method for consistency like you suggest.

The array syntax seems the most versatile and the variadic always felt a little weird. If it is an easy fix (to make them work consistently) then I say we do it, if it is not then perhaps we drop official support for the variadic function call and un-document it?

**Comment by sastan** [comment]
I'm unsure if variants should cross string boundaries. Maybe the object syntax would be a solution here:

@rockmandash What do you think about this one:

```js
tw(["bg-pink-50", { hover: ["text-pink-900", "p-3"] }])
```

**Comment by rockmandash** [comment]
@sastan I'm not sure, sorry!

**Comment by lukejacksonn** [comment]
I don't think it makes sense at all for variants to cross string boundaries. Unless I am missing something, each individual argument should be processed as if it was being passed as a single argument. I'm also reasonably confident that no one else is expecting this behaviour either.

Currently the issue is that this:

```js
tw('hover:bg-red-500', 'p-3')
```

Behaves like this:

```js
tw('hover:(bg-red-500 p-3)')
```

Which is not expected behaviour, at least I would not have expected that to be the case. Either we stop variants crossing string boundaries in variadic argument input or drop support for variadic arguments entirely for now.

**Comment by sastan** [comment]
I'm working a PR

**Comment by sastan** [comment]
It is now consistent with the array method:

```js
tw('hover:bg-red-500', 'p-3')
tw(['hover:bg-red-500', 'p-3'])
// => hover:bg-red-500 p-3
```

If you want grouping to cross string boundaries you can use explicit grouping:

```js
tw('hover:(', 'bg-red-500', 'p-3', ')', 'm-1')
// => hover:bg-red-500 hover:p-3 m-1

tw('hover:(bg-red-500', 'p-3)', 'm-1')
// => hover:bg-red-500 hover:p-3 m-1
```

**Comment by sastan** [comment]
@rockmandash I don't know where i got this from... I think some tweetet it:

```
directives: {
   tw: {
     inserted(el, binding) {
       el.className = tw`${binding.value}`
     },
   },
 },

// ------

<div v-tw="'h-screen bg-purple-400 flex items-center justify-center'">Awesome twind</div>
```

Maybe this helps with your project.

**Comment by rockmandash** [comment]
@sastan OMG, that is way too cool!

Definitely going to give it a try!

**Comment by sastan** [comment]
If you have something for the docs/examples.md you could create an PR for vue 🤩
