### ISSUE TITLE
[Bug]: Can't suppress `TWIND_INVALID_CLASS` warning while DEV of the browser console

### ISSUE THREAD

**Issue by subuta** [tw-in-js/twind#403]
### Reproduction

Any front-end code contains invalid Twind class causes https://github.com/tw-in-js/twind/blob/v1.0.1/packages/core/src/internal/warn.ts#L18 triggered.

### Without `cancelable` (current implementation in the Twind)

<img width="505" alt="image" src="https://user-images.githubusercontent.com/6227288/205244509-4a5fb566-3cbc-414a-9ce5-c24215ef1691.png">

### Describe the bug

After upgrading `Twind` to v1. I noticed console shows a lot of `TWIND_INVALID_CLASS` warning. I know these class reported in the `TWIND_INVALID_CLASS` are valid for my usage. and want to find a way to suppress that warning.

then I found this documentation in the [twind/CHANGELOG.md at v1.0.1 · tw-in-js/twind](https://github.com/tw-in-js/twind/blob/v1.0.1/packages/twind/CHANGELOG.md). but this didn't work when I try implement custom `addEventListener('warning', (event) => {}` as suggested.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/6227288/205245241-dec8fb83-9bf5-453f-af90-925399c5bca9.png">

-----

After checking Twind's source code. I found current implmentation of `warning` CustomEvent didn't pass necessary parameter `cancelable: true` to constroctor. that cause developer can't suppress `warning` message of the Twind.

### Without `cancelable` (current implementation in the Twind)

<img width="505" alt="image" src="https://user-images.githubusercontent.com/6227288/205244509-4a5fb566-3cbc-414a-9ce5-c24215ef1691.png">

### With `cancelable: true` (Should be)

<img width="628" alt="image" src="https://user-images.githubusercontent.com/6227288/205244097-440957e5-a371-45b9-bce5-b7de20f55386.png">

### Severity

annoyance

### System Info

```sh
Chrome: Version 108.0.5359.71 (Official Build) (x86_64)
Package: @twind/core `v1.0.1`
```

### Additional Information

Nothing

**Comment by wzulfikar** [comment]
Hey @sastan, I recently face this issue in Storybook and I can confirm the fix is working. Below is the codesandbox for before and after the fix. Pls let me know if I can put it as a PR ([changeset](https://github.com/tw-in-js/twind/compare/main...wzulfikar:twind:wzulfikar/add-cancelable-to-event)).

Before the fix ([csb link](https://codesandbox.io/p/github/wzulfikar/csb-storybook-twind-invalid-class-warning/main?file=%2F.storybook%2Fpreview.js)), `event.preventDefault()` doesn't actually do anything. Both the actual warnings and my "twind warning" are shown:

![image](https://user-images.githubusercontent.com/7823011/206516681-7fe9b3aa-ef64-455f-94ae-5c08963f0d99.png)

After the fix ([csb link](https://codesandbox.io/p/github/wzulfikar/csb-storybook-twind-invalid-class-warning/with-fix?file=%2F.storybook%2Fpreview.js)), only my "twind warning" are shown:

![image](https://user-images.githubusercontent.com/7823011/206517069-489bb69f-0db9-4453-a410-eea26b5a97b6.png)

**Comment by subuta** [comment]
Ah, Sorry for being late to be noticed. and Many Thanks for the PR @wzulfikar @sastan 🙏
