### ISSUE TITLE
[Bug]: Extension does not work on windows

### ISSUE THREAD

**Issue by emilkrebs** [tw-in-js/twind#471]
### Reproduction

Download the twind vscode-extension and use it inside a fresh (https://fresh.deno.dev/) project.
As you may see, you don't get autocompletion. 

However, if you try the same on MacOS it works fine. 

Please fix this, it's really slowing down the workflow.

### Describe the bug

You don't get any autocompletion from the Windows VSCode extension, but on MacOS it works fine.

### Severity

serious, but I can work around it

### System Info

```sh
## Binaries:
 - Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
 - Internet Explorer: 11.0.22621.1
```

**Comment by JuerGenie** [comment]
Oops, this extension doesn’t work on `typescript@^5.0.0` yet.
About your problem, it might be because `VSCode v.1.65` upgraded the built-in `typescript` to `5.0`. Another thing you can try is switching your vscode’s typescript lib to `typescript@^4.0.0`.

It’s working for me, and I hope it works for you too 😄.
